apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapsapi-deployment
spec:
  selector:
    matchLabels:
      app: mapsapi
  replicas: 1
  template:
    metadata:
      labels:
        app: mapsapi
    spec:
      containers:
        - name: mapsapi
          image: mapsapi
          ports:
            - containerPort: 3000
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: mapsapi-service
spec:
  selector:
    app: mapsapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31001
